version: '3.8'

services:
  jules_api:
    build: .
    container_name: jules_poc_api_container
    command: ["/app/wait-for-it.sh", "db", "5432", "python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/jules_db

  db:
    image: postgres:14-alpine
    container_name: jules_poc_db_container
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jules_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
